### ISSUE TITLE
[OneWayGriefing] Fix increaseStake() such that funds are taken from msg.sender

### ISSUE THREAD

**Issue by thegostep** [erasureprotocol/erasure-protocol#137]

**Comment by kenchangh** [comment]
@thegostep should this apply to the `punish` function too?

Currently the `punish` function looks like this:

```
function punish(address from, uint256 currentStake, uint256 punishment, bytes memory message) public returns (uint256 cost) {
        // restrict access
        require(isCounterparty(msg.sender) || Operated.isActiveOperator(msg.sender), "only counterparty or active operator");

        // execute griefing
        cost = Griefing._grief(from, _data.staker, currentStake, punishment, message);
    }```

So if we were to change it to use `msg.sender`, it would look like this:

```
function punish(uint256 currentStake, uint256 punishment, bytes memory message) public returns (uint256 cost) {
        // restrict access
        require(isCounterparty(msg.sender) || Operated.isActiveOperator(msg.sender), "only counterparty or active operator");

        // execute griefing
        cost = Griefing._grief(msg.sender, _data.staker, currentStake, punishment, message);
    }
```

**Comment by thegostep** [comment]
The stronger assumption of always taking funds from msg.sender is necessary to avoid relying on approval amounts to control access to funds on the contract
