### ISSUE TITLE
Bring currentStake to top level by requiring as input to punish()

### ISSUE THREAD

**Issue by thegostep** [erasureprotocol/erasure-protocol#164]
https://github.com/erasureprotocol/erasure-protocol/blob/0271f9b35b3027c9294535d6a51029e76e5bab18/contracts/modules/Griefing.sol#L54

**Comment by kenchangh** [comment]
Fixed with https://github.com/erasureprotocol/erasure-protocol/pull/169/commits/644bcd482a7b922800943b5e1376a626b0616573

**Comment by kenchangh** [comment]
Fixed with https://github.com/erasureprotocol/erasure-protocol/pull/169/commits/644bcd482a7b922800943b5e1376a626b0616573
