### ISSUE TITLE
TwoWay or not TwoWay

### ISSUE THREAD

**Issue by thegostep** [erasureprotocol/erasure-protocol#165]
Should the default behaviour of a mutual griefing agreement to create two OneWayGriefing agreements or to create one TwoWayGriefing agreement?

### in favor of TwoWay
- Don't need to link the agreements through metadata
- Less gas cost on deployment
- Built in synchrony for countdown

### in favor of OneWay
- Less room for error on implementation because less code complexity
- Less room for error on app side by having clear role on the contract
- Consistency in synchrony for start of griefing and end of griefing (needs to be done in wrapper)

**Comment by kenchangh** [comment]
I don't understand these points

>Built in synchrony for countdown
>Consistency in synchrony for start of griefing and end of griefing (needs to be done in wrapper)

Isn't the CountdownGriefing contract going to be used anyway to implement countdowns? How does it relate to One Way or Two Way?

**Comment by kenchangh** [comment]
Fixed with PR https://github.com/erasureprotocol/erasure-protocol/pull/169
