### ISSUE TITLE
Post registry should be fetched internally

### ISSUE THREAD

**Issue by thegostep** [erasureprotocol/erasure-protocol#168]
https://github.com/erasureprotocol/erasure-protocol/blob/0271f9b35b3027c9294535d6a51029e76e5bab18/contracts/posts/Feed_Factory.sol#L41

**Comment by kenchangh** [comment]
Fixed in https://github.com/erasureprotocol/erasure-protocol/pull/187

**Comment by thegostep** [comment]
The fix in #187 is not sufficient since it not compatible with the use of `create()`

Should opt for calling the getter `getInstanceRegistry()` on the factory interface.
