### ISSUE TITLE
releaseStake should allow for partial amounts

### ISSUE THREAD

**Issue by jparyani** [erasureprotocol/erasure-protocol#170]
See https://github.com/numerai/tournament-contracts/blob/db5d434b99c6f2e9f8f1f86887502b4abb106e72/contracts/erasure/agreements/SimpleGriefing.sol#L92 where I already implemented it on the tournament side.

**Comment by kenchangh** [comment]
Addressed in https://github.com/erasureprotocol/erasure-protocol/pull/173
