### ISSUE TITLE
Use of multihash adds complexity and the decision is not explicitly justified

### ISSUE THREAD

**Issue by fulldecent** [erasureprotocol/erasure-protocol#258]
Currently the design specifies, and implementation uses, multihash for data security and immutability. It could be that the purpose of choosing multihash is to enable IPFS file storage (i.e. IPLD).

If data will be used on-chain then only the blockchain native hashing format will be useful, and it is unnecessary to specify a hash format and bit length. If a hash will be used off-chain then it doesn’t matter what format and bit length is used because the skeptic will verify the provided content offline.

**Recommendation: IPFS compatibility (the design goal) should be explicitly mentioned every time that multihash (implementation detail) is introduced.**
References:

* Multihash storage is two EVM words (versus one for a SHA-256 hash): https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/modules/MultiHashWrapper.sol#L13-L17
* Design specifies multihash https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/README.md#track-record-through-posts-and-feeds

**Comment by thegostep** [comment]
@fulldecent I have gone back and forth on this. I tend to agree that a simple bytes32 sha256 hash gets the job done. I am wondering if you think there is a case for using a plain bytes field which would support other content identification techniques?

**Comment by fulldecent** [comment]
Basically you have two good choices:

1. `bytes` -- fully extensible, but you can't use it on-chain because it is fully extensible
2. `bytes32 (sha256)` -- works with IPFS and every known technology for at least the next 10 years, and it only uses one storage word

I would choose option 2 and then budget for rewriting all of the code at least once in the next 10 years :-)
