### ISSUE TITLE
Posts and feeds are not differentiated

### ISSUE THREAD

**Issue by fulldecent** [erasureprotocol/erasure-protocol#259]
There is significant overlap between posts and feeds. Looking at implementation details (they’re in the same folder, similar code),  and documentation (post is mentioned prominently but feed is not) it seems like one was an afterthought of the other.

The only practical difference is that a post can be read on-chain and it is more expensive to make and it can only be done once.

|                           | Post                   | Feed             |
| ------------------------- | ---------------------- | ---------------- |
| Can post data             | 😔 Once                 | 😄 Many times     |
| Data format               | Multihash              | Hash             |
| Posting cost              | 😞 Expensive (`SSTORE`) | 😄 Cheap (`LOG3`) |
| Can post metadata updates | ✅                      | ✅                |
| Can be read on-chain      | ✅                      | ❌                |

There is no use case presented in documentation where current on-chain (`SSTORE`) data is useful. I cannot think of any on-chain contract that would want to purchase data using Erasure.

**Recommendation: remove `Post` and `ProofHash` contracts. In the documentation continue to talk about feeds and posts. But actually a post will be implemented just as a feed with only one entry.**

References:

* Post implementation: https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/posts/Post.sol
* Feed implementation: https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/posts/Feed.sol

**Comment by thegostep** [comment]
Hypothetical use case for on chain read: An escrow which validates that the data sold matches the data in the feed before finalizing. Admittedly not something currently feasible, but I wonder if some zkp magic could get it done?

I agree it makes sense to follow recommendation until concrete demand. @jgeary for input.

**Comment by fulldecent** [comment]
Yes, I am all about ZKP magic and these types of applications. Although they are probably a ways off.

My mantra: building the product before concrete demand restricts one from build the fitter product when the specific demand is known
