### ISSUE TITLE
Some of the API surface is unnecessary and/or duplicative

### ISSUE THREAD

**Issue by fulldecent** [erasureprotocol/erasure-protocol#266]
The public and external functions are the contracts’ surface area. Some of these functions provide little if any incremental value to the public.

Recommendation: reconsider if these functions are necessary to be public:

- [escrows/CountdownGriefingEscrow.sol](https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/escrows/CountdownGriefingEscrow.sol) : `function isBuyer(address caller) public view returns (bool validity) {`
- [escrows/CountdownGriefingEscrow.sol](https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/escrows/CountdownGriefingEscrow.sol) : `function isSeller(address caller) public view returns (bool validity) {`
- [escrows/CountdownGriefingEscrow.sol](https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/escrows/CountdownGriefingEscrow.sol) : `function isOpen() public view returns (bool validity) {`
- [escrows/CountdownGriefingEscrow.sol](https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/escrows/CountdownGriefingEscrow.sol) : `function onlyStakeDeposited() public view returns (bool validity) {`
- [escrows/CountdownGriefingEscrow.sol](https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/escrows/CountdownGriefingEscrow.sol) : `function onlyPaymentDeposited() public view returns (bool validity) {`
- [escrows/CountdownGriefingEscrow.sol](https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/escrows/CountdownGriefingEscrow.sol) : `function isDeposited() public view returns (bool validity) {`
- [escrows/CountdownGriefingEscrow.sol](https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/escrows/CountdownGriefingEscrow.sol) : `function isFinalized() public view returns (bool validity) {`
- [escrows/CountdownGriefingEscrow.sol](https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/escrows/CountdownGriefingEscrow.sol) : `function isCancelled() public view returns (bool validity) {`
- [agreements/CountdownGriefing.sol](https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/agreements/CountdownGriefing.sol) : `function isStaker(address caller) public view returns (bool validity) {`
- [agreements/CountdownGriefing.sol](https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/agreements/CountdownGriefing.sol) : `function isCounterparty(address caller) public view returns (bool validity) {`
- [agreements/CountdownGriefing.sol](https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/agreements/CountdownGriefing.sol) : `function isStaked() public view returns (bool validity) {`
- [agreements/CountdownGriefing.sol](https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/agreements/CountdownGriefing.sol) : `function isInitialized() public view returns (bool validity) {`
- [agreements/CountdownGriefing.sol](https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/agreements/CountdownGriefing.sol) : `function isInCountdown() public view returns (bool validity) {`
- [agreements/CountdownGriefing.sol](https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/agreements/CountdownGriefing.sol) : `function isTerminated() public view returns (bool validity) {`
- [agreements/SimpleGriefing.sol](https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/agreements/SimpleGriefing.sol) : `function isStaker(address caller) public view returns (bool validity) {`
- [agreements/SimpleGriefing.sol](https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/agreements/SimpleGriefing.sol) : `function isCounterparty(address caller) public view returns (bool validity) {`
- [agreements/SimpleGriefing.sol](https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/agreements/SimpleGriefing.sol) : `function isInitialized() public view returns (bool validity) {`
- [agreements/SimpleGriefing.sol](https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/agreements/SimpleGriefing.sol) : `function isStaked() public view returns (bool validity) {`
- [modules/Griefing.sol](https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/modules/Griefing.sol) : `function getPunishment(uint256 ratio, uint256 cost, RatioType ratioType) public pure returns(uint256 punishment) {`
- [modules/Operated.sol](https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/modules/Operated.sol) : `function isOperator(address caller) public view returns (bool ok) {`
- [modules/Operated.sol](https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/modules/Operated.sol) : `function isActiveOperator(address caller) public view returns (bool ok) {`
- [modules/Template.sol](https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/modules/Template.sol) : `function isCreator(address caller) public view returns (bool ok) {`

**Comment by thegostep** [comment]
@fulldecent The rationale for this design decision is to prioritize ease of composability over ABI simplicity. The idea is that having access to bools avoids the need to import the enum with the interface. That being said, I've seen the chaos it causes on etherscan. Does this rationale make sense?

**Comment by fulldecent** [comment]
People will already be importing the enums with the interface. That type safety comes for free when people use your interfaces. Just like when you import iERC20.sol you get all the function definitions you need.

The risk that this additional ease of compostability brings is that people might not understand what the bools mean. They may not understand that they are mutually exclusive. The status enum is obviously exclusive. The one I was specifically worried about was `isOpen()`. I am sure somebody will intuitively believe that has a different meaning that what I found it means by reading the code.

Your rationale is good and a strong focus on single-purpose functions for downstream users is a reason to close this issue (AFTER adding great documentation for `isOpen()` and others).

**Comment by thegostep** [comment]
After thinking about it some more, I am in favour of simplifying the ABI
