### ISSUE TITLE
Implementation of multihash is not future proof

### ISSUE THREAD

**Issue by fulldecent** [erasureprotocol/erasure-protocol#274]
The implementation of multihash is pegged to 256-bit hashes. This is effectively hard-coding to the current/prior version of IPFS. This means it is not a compliant implementation of multihash and it is not forward compatible with IPLD.

The design motivation of Erasure seems to be the sale of secret files over the span of days/ weeks/ months. 

The current version of IPFS/CID uses SHA-256 which seems safe for the foreseeable future. And future versions of IPFS are likely to support SHA-256 CIDs (CIDv0/CIDv1) indefinitely. This means adopting only SHA-256 may be a reasonable tradeoff.

Dropping IPLD forward compatibility and pegging to SHA-256 will retain compatibility with IPFS while only requiring one storage slot (256 bits) versus the current two (saves 20,000 gas for `Post`).

**Recommendation: reconsider the benefits of strict compliance with IPLD**

References:

* Implementation requires 256 bit hashes (34 bytes including headers) https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/modules/MultiHashWrapper.sol#L44
* IPFS content identifiers: https://docs.ipfs.io/guides/concepts/cid/
* IPFS content identifier evolution https://github.com/ipfs/specs/issues/130

**Comment by thegostep** [comment]
deprecated use of multihash
