### ISSUE TITLE
Implementation of multihash does not adhere to its documentation

### ISSUE THREAD

**Issue by fulldecent** [erasureprotocol/erasure-protocol#275]
_splitMultiHash is documented as Given a base58-encoded  hash, divides into its individual parts and returns a struct but actually, base58 encoding is not performed. Actually, the code is expecting binary encoding.

Recommendation: Correct all mentions of “base58” in the documentation.

References:

- https://github.com/erasureprotocol/erasure-protocol/blob/0271f9b35b3027c9294535d6a51029e76e5bab18/contracts/modules/MultiHashWrapper.sol#L38

**Comment by thegostep** [comment]
deprecated use of multihash
