### ISSUE TITLE
💣 The function getPunishment is inaccurate

### ISSUE THREAD

**Issue by fulldecent** [erasureprotocol/erasure-protocol#276]
In the `Griefing` contract, the function `getPunishment` exists to show the amount of punishment that is achievable for a given amount of cost.

The function returns incorrect values for two reasons:

1. The punishment amount is not limited by the maximum amount staked.
2. The `getPunishment` function uses multiplication but the actual `getCost` function which is used employes division. Due to quantization effects, division is not the inverse of multiplication. (e.g. 1÷3×3 ≠ 1)

**Recommendation: remove the `getPunishment` function entirely because it can never be accurate.**

References:

* https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/modules/Griefing.sol#L91

**Comment by thegostep** [comment]
Undecided on this one. I think having the function is worthwhile for reference purposes despite rounding error.

**Comment by fulldecent** [comment]
That's fair to keep it.

**Alternate recommendation: document in the function that the result is approximate due to rounding/quantization**
