### ISSUE TITLE
⚠️ Inconsistent type usage: countdownLength, ratio

### ISSUE THREAD

**Issue by fulldecent** [erasureprotocol/erasure-protocol#279]
Some countdowns use 128 bits, others use 256. Some ratio use 256 bits, some use 120 bits.

Although appropriate checking is used for `ratio` (the `ratio = uint256(uint120(ratio))` check), this approach is dangerous and is underdocumented in the code (the invariant should be documented where ratio is defined).

Also, `ratio` is elsewhere called `griefCostToPunishment`.

**Recommendation: use consistent type choices for similar variables.**

**Recommendation: choose between `ratio` and `griefCostToPunishment` and use it consistently.**

The Solidity language should be updated to make this easier. Issue sent.

References:

* countdownLength 128 bits: https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/escrows/CountdownGriefingEscrow.sol#L36
* countdownLength 256 bits: https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/escrows/CountdownGriefingEscrow.sol#L45
  * ratio 120 bits: https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/escrows/CountdownGriefingEscrow.sol#L420
* ratio 256 bits: https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/agreements/CountdownGriefing.sol#L41
* Solidity issue: https://github.com/ethereum/solidity/issues/7728

**Comment by thegostep** [comment]
In this case, the downcasting is worthwhile for gas optimization purposes. Added note on initialize function.

Could not find any reference to griefCostToPunishment

**Comment by fulldecent** [comment]
`griefCostToPunishment` already gone. That was from WIP folder which is deleted.

I have read read the updated documentation and could not follow the explanation based on what is written.
