### ISSUE TITLE
Enumeration status do not use zero for final state

### ISSUE THREAD

**Issue by fulldecent** [erasureprotocol/erasure-protocol#280]
In all of the `enum`s, the zero-position value is the opening state. However the contract spends a majority of its life in the final state. This could be wasteful.  (`SSTORE` zero recovers gas.)

**Recommendation: identify if this optimization is worth pursuing. Then consider what percentage of contracts are likely to get to the final state. Then consider to set the final enumeration state to be at the zero position.**

References:

* https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/escrows/CountdownGriefingEscrow.sol#L433

**Comment by thegostep** [comment]
I prefer to have the initial state be null since it saves gas up front.
