### ISSUE TITLE
MultiHashWrapper and Spawner are more appropriate to be libraries

### ISSUE THREAD

**Issue by fulldecent** [erasureprotocol/erasure-protocol#281]
Currently `contract MultiHashWrapper` is implemented as a contract. Because this module has no storage and no external functions, it is appropriate to implement this as a library.
Similarly for `Spawner`.

**Recommendation: switch these to libraries**
References:

* MultiHashWrapper implementation: https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/modules/MultiHashWrapper.sol#L10
* Spawner implementation: https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/modules/Spawner.sol

**Comment by thegostep** [comment]
@fulldecent Using a library for Spawner would add gas overhead of a delegate call for every clone produced. I don't see a benefit for it?

**Comment by fulldecent** [comment]
A "library" contract with no external functions is implemented a little differently. 

> ... code of internal library functions and all functions called from therein will at compile time be pulled into the calling contract, and a regular `JUMP` call will be used instead of a `DELEGATECALL`.
> 
> https://solidity.readthedocs.io/en/v0.5.13/contracts.html#libraries

So basically `contract` and `library` are equivalent here and the choice can be made based on which ever is semantically preferred or easier to reason about.

**Comment by thegostep** [comment]
Ah, I see. Will keep as is for now
