### ISSUE TITLE
Purpose of Operated. _status is unclear

### ISSUE THREAD

**Issue by fulldecent** [erasureprotocol/erasure-protocol#283]
The purpose of _status is unclear. All functions based on this variable seem to have no end-user value.

**Recommendation: First consider if this is needed at all. Please note that messages cannot be sent by `address(0)` so currently, all status check is redundant.**

**Review if `_activateOperator`, `_deactivateOperator`, `_transferOperator`, `_renounceOperator`, `hasActiveOperator`, `isActiveOperator` are necessary.** 

**If keeping, consider switching `_status` to an enum or adding documentation.**

**If removing, just check whether the operator is `address(0)`**

References: 

* Definition: https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/modules/Operated.sol

**Comment by thegostep** [comment]
agree status is redundant
