### ISSUE TITLE
Operator module functions are WET

### ISSUE THREAD

**Issue by fulldecent** [erasureprotocol/erasure-protocol#284]
Every subclass of `Operator` includes identical public functions to access the internal base class function.

This code duplication reduces readibility and increases the risk of errors.

**Recommendation: make the base class functions public and remove the identical subclass copies**

References: 

* Base `internal` implementation: https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/modules/Operated.sol#L29

* Example of copy: https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/posts/Feed.sol#L97

**Comment by thegostep** [comment]
This would break the invariant that all public state changing functions are defined at the top of the inheritance tree. Decision is keep status quo in order to facilitate definition of access control
