### ISSUE TITLE
isCreator can be removed from API surface

### ISSUE THREAD

**Issue by fulldecent** [erasureprotocol/erasure-protocol#285]
This function provides limited utility to the public, since `getCreator` is already available.

Also, every use of `isCreator` is from a subclass checking for access control and those subclasses are all `Operated`.

**Recommendation: consider to have `Template` subclass from `Operated` and charge `isCreator` from a public function into an internal modifier.**

References:

* Definition: https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/modules/Template.sol#L34

**Comment by thegostep** [comment]
Keeping Template separate but changing isCreator to internal
