### ISSUE TITLE
Variety of approaches is used for restricting actor for permission checking

### ISSUE THREAD

**Issue by fulldecent** [erasureprotocol/erasure-protocol#292]
In `CountdownGriefingEscrow`, the function `depositPayment()` checks using:

```solidity
if (!isBuyer(msg.sender) && !Operated.isActiveOperator(msg.sender)) {
    require(_data.buyer == address(0), "only buyer or active operator");
...
```

And `depositStake()` does similarly.

These are equivalent to an alternate approach used for the rest of the code, for example `finalize()`:

```solidity
require(isBuyer(msg.sender) || Operated.isActiveOperator(msg.sender), "only buyer or active operator");
```

Using a variety of approaches to perform the same task reduces code readability.

**Recommendation: update `depositPayment()` and ``depositStake()` to use the mechanism as per neighboring code.**

**Comment by thegostep** [comment]
completed
