### ISSUE TITLE
⚠️ submitHash does NOT accept multihashes

### ISSUE THREAD

**Issue by fulldecent** [erasureprotocol/erasure-protocol#294]
In `Feed.submitHash()` , the user-visible documentation shaws the input as:

> Proofhash (34 bytes) of the timestamped data as a base58-encoded multihash

However the actual input is a 256-bit hash (not a multihash).

**Recommendation: update the documentation**

References:

* Function documentation: https://github.com/erasureprotocol/erasure-protocol/blob/4a3d98ce023a264a9f3c7ba62ef77a9207bba5fe/contracts/posts/Feed.sol#L61

**Comment by thegostep** [comment]
fixed by 0d59cb4
